apiVersion: apps/v1
kind: Deployment

metadata:
  name: 006-devops-nextjs-kubernetes-jenkins-pipeline
  labels:
    app: 006-devops-nextjs-kubernetes-jenkins-pipeline
    team: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: 006-devops-nextjs-kubernetes-jenkins-pipeline

  template:
    metadata:
      labels:
        app: 006-devops-nextjs-kubernetes-jenkins-pipeline

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: 006-devops-nextjs-kubernetes-jenkins-pipeline
          image: huseyin11/006-devops-nextjs-kubernetes-jenkins-pipeline:latest
          imagePullPolicy: Always

          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"

          ports:
            - containerPort: 3000